version: '3.1'
services:
  web:
    image: gitlab/gitlab-ce:15.10.8-ce.0
    depends_on:
      - mydb
    ports:
      - "8080:80"
    environment:
    - HOST=mydb
    - USER=gitlab
    - PASSWORD=gitlab
  mydb:
    image: postgres:14.7
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=gitlab
      - POSTGRES_USER=gitlab