apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab-deployment
  namespace: default
  labels:
    app: gitlab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitlab
  template:
    metadata:
      labels:
        app: gitlab
    spec:
      containers:
      - name: gitlab
        image: gitlab/gitlab-ce:15.10.8-ce.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: HOST
          value: postgres-service-gitlab
        - name: USER
          value: admin
        - name: PASSWORD
          value: root
