apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gitlab-ingress
  namespace: default
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - demo.localdev.me
  rules:
  - host: demo.localdev.me
    http:
      paths:
      - backend:
          service:
            name: gitlab-service
            port:
              number: 8069
        path: /
        pathType: Prefix