apiVersion: v1
kind: Service
metadata:
  name: postgres-service-gitlab
  labels:
    app: postgres-gitlab
spec:
  type: ClusterIP
  ports:
    - port: 5432 
      targetPort: 5432
  selector:
    app: postgres-gitlab

  